### ISSUE TITLE
X-plane crashes

### ISSUE THREAD

**Issue by fpuentegomez** [retostockli/xpcockpit#1]
Hello,

I simply downloaded, compiled and make install xpserver and copied the plugin as per de instructions. Now X-plane crashes.

X-Plane: 10.51 64 bit (also tried 32bit and same result).

Here's the log.txt

[Log.txt](https://github.com/retostockli/xpcockpit/files/4430612/Log.txt)

Cheers and thank you for your time

**Comment by retostockli** [comment]
Ok, let us trace this. I have not used X-Plane 10 for a while, but I think that we should get the plugin running on XP10 since I have not changed anything on the plugin part for a while.
Can you type for me in the xpserver plugin directory to see if you have unmet dependencies:
ldd lin.xpl

And post the output here. As a next step we'll exchange your plugin and I try to load it in XP11. And if that works, I try to re-install XP10 on my side and try it. Ok?

**Comment by fpuentegomez** [comment]
Hello again,

First off, thank you so much for the quick response.

The output from ldd lin.xpl is:
`	linux-vdso.so.1 (0x00007ffd67774000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f1e8c64d000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f1e8c487000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f1e8c7db000)`

Best regards

**Comment by retostockli** [comment]
Looks sane. Same as on my side. No missing dependencies. Could you pack the content of the dist folder where the plugin resides into a zip and send it to me (reto dot stockli at gmail)? I will then try to load it on xp11. If that works I'll re-install xp10.

One small question: can you confirm that you copied (or linked) the whole xpserver directory into the plugins directory? The xpserver directory should contain the 32, 64 and xpserver.ini files.

**Comment by fpuentegomez** [comment]
Issue fixed, should already be in the last update to the xpserver folder.
Cheers
